In [1]:
%load_ext autoreload
%autoreload 2

import sys

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from scipy import stats

sns.set_style('whitegrid')

In [35]:
j = 1

In [45]:
thetas = []

for i in range(100000):
    theta = np.random.dirichlet([1,1,1])
    z = np.random.multinomial(1, theta)

    if np.argmax(z) == j:
        thetas.append(theta)

In [52]:
np.array(thetas).mean(0)

array([0.24970284, 0.49990074, 0.25039642])

In [55]:
np.random.dirichlet([1,2,1], size=100000).mean(0)

array([0.24922341, 0.50026856, 0.25050803])

In [79]:
j = 1
z = -1
while True:
    theta = np.random.dirichlet([1,1,1])
    zs = np.random.multinomial(1, theta)
    z = np.argmax(zs)
    if z == j:
        print(theta)
        break

[0.43349294 0.33589964 0.23060743]
